services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: RelaxGaming
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: java-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
    command: ["sh", "-c", "./wait-for-it.sh db:3306 -- java -cp .:mysql.jar GameServer"]
